// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsTJ_ERprp3COefBT1BAQtLSsdG3yAtk8',
    appId: '1:629313238411:web:963d1a02ef76738b0deb8e',
    messagingSenderId: '629313238411',
    projectId: 'flutter-d3a7f',
    authDomain: 'flutter-d3a7f.firebaseapp.com',
    databaseURL: 'https://flutter-d3a7f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-d3a7f.appspot.com',
    measurementId: 'G-QTD9VHZP4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB16RgZnMvr8o4KTsBx6yMsttbYQWsOTo',
    appId: '1:629313238411:android:a308084f7131b74d0deb8e',
    messagingSenderId: '629313238411',
    projectId: 'flutter-d3a7f',
    databaseURL: 'https://flutter-d3a7f-default-rtdb.firebaseio.com',
    storageBucket: 'flutter-d3a7f.appspot.com',
  );
}
